---  # document start

################
# CONFIG FILE  #
################

fps: 60

display_shell_interface: false
display_audio_interface: false

n_rolling_history: 4
number_of_audio_samples: 24

audio_ports:
  -
    name: Built-in Microphone
    min_frequency: 200
    max_frequency: 12000
    sampling_rate: 44000
    number_of_audio_samples: 24
    min_volume_threshold: 1e-7

strips:
  # -
  #   name: Desk Corner
  #   serial_port_name: /dev/tty.usbserial-14210
  #   max_brightness: 120
  #   associated_midi_channels:
  #     - Audio2Led Synth
  #   midi_ports_for_changing_mode:
  #     - Audio2Led ChangeMod
  #   real_shape:
  #     - 252
  #   shapes:
  #     -
  #       - 148
  #       - 104
  #     -
  #       - 74
  #       - 74
  #       - 52
  #       - 52
  #   active_audio_channel_index: 0
  #   active_color_index: 0
  #   active_shape_index: 0
  #   is_reverse: false
  #   bpm: 120
  #   is_mirror: true
  #   active_color_scheme_index: 0
  #   color_schemes:
  #     - # pink blue
  #       - "#FF00C8"
  #       - "#00EDFF"
  #     - # orange blue
  #       - "#FFA200"
  #       - "#00C6FF"
  #     - # red green
  #       - "#FF002E"
  #       - "#00FFA4"
  #     - # purple green
  #       - "#F900FF"
  #       - "#22FF00"
  #     - # blue yellow
  #       - "#0024FF"
  #       - "#FFE500"
  #     -
  #       - red
  #       - green
  #       - blue
  #     -
  #       - red
  #     -
  #       - green
  #     -
  #       - blue
  #     -
  #       - white
  #     -
  #       - "#FF00C8"
  #
  #   active_visualizer_effect: scroll

  -
    name: Front Desk
    serial_port_name: /dev/tty.usbserial-14220
    max_brightness: 120
    associated_midi_channels:
      - Audio2Led Synth
    midi_ports_for_changing_mode:
      - Audio2Led ChangeMod
    real_shape:
      - 50
    shapes:
      -
        - 50
      -
        - 25
        - 25
      # -
      #   - 126
      #   - 126
      # -
      #   - 62
      #   - 62
      #   - 62
      #   - 62

    active_audio_channel_index: 0
    active_color_index: 0
    active_shape_index: 0
    is_reverse: false
    bpm: 120
    is_mirror: false
    active_color_scheme_index: 0
    color_schemes:
      -
        - red
        - green
        - blue
      -
        - red
      -
        - green
      -
        - blue
      -
        - white
      -
        - "#FF00C8"

    active_visualizer_effect: piano
  #
  # -
  #   name: Lantern
  #   serial_port_name: /dev/tty.usbserial-14230
  #   max_brightness: 120
  #   associated_midi_channels:
  #     - Audio2Led Synth
  #   midi_ports_for_changing_mode:
  #     - Audio2Led ChangeMod
  #   real_shape:
  #     - 34
  #   shapes:
  #     -
  #       - 34
  #     -
  #       - 12
  #       - 12
  #   active_audio_channel_index: 0
  #   active_color_index: 0
  #   active_shape_index: 0
  #   is_reverse: false
  #   bpm: 120
  #   is_mirror: true
  #   active_color_scheme_index: 0
  #   color_schemes:
  #     - # pink blue
  #       - "#FF00C8"
  #     - # orange blue
  #       - "#FFA200"
  #       - "#00C6FF"
  #     - # red green
  #       - "#FF002E"
  #       - "#00FFA4"
  #     - # purple green
  #       - "#F900FF"
  #       - "#22FF00"
  #     - # blue yellow
  #       - "#0024FF"
  #       - "#FFE500"
  #     -
  #       - red
  #       - green
  #       - blue
  #     -
  #       - red
  #     -
  #       - green
  #     -
  #       - blue
  #     -
  #       - white
  #     -
  #       - "#FF00C8"
  #
  #   active_visualizer_effect: scroll
  #

...  # document end
