---  # document start

################
# CONFIG FILE  #
################

# -
#   - 20
#   - 18
#   - 18
#   - 18

fps: 60

display_shell_interface: false
display_audio_interface: false

n_rolling_history: 4
number_of_audio_samples: 24

audio_ports:
  -
    name: Built-in Microphone
    min_frequency: 200
    max_frequency: 12000
    sampling_rate: 44000
    number_of_audio_samples: 24
    min_volume_threshold: 1e-7
  # -
  #   name: Loopback Audio 2
  #   min_frequency: 200
  #   max_frequency: 12000
  #   sampling_rate: 44000
  #   number_of_audio_samples: 24
  #   min_volume_threshold: 1e-7

strips:
  -
    serial_port_name: /dev/tty.usbserial-14210
    max_brightness: 120
    associated_midi_channels:
      - Ableton-virtual-midi-ouput RightSynth
    midi_ports_for_changing_mode:
      - Ableton-virtual-midi-ouput ChangeModStripOne
      - Ableton-virtual-midi-ouput ChangeMod
    shapes:
      -
        - 252
      -
        - 126
        - 126
      -
        - 62
        - 62
        - 62
        - 62
      -
        - 30
        - 30
        - 30
        - 30
        - 30
        - 30
        - 30
        - 30
    active_audio_channel_index: 0
    active_color_index: 0
    active_shape_index: 0
    is_reverse: false
    bpm: 120
    is_mirror: true
    active_color_scheme_index: 0
    color_schemes:
      -
        - "#FF00C8"
        - "#00EDFF"
      -
        - red
        - green
        - blue

    active_visualizer_effect: scroll

  # -
  #   serial_port_name: /dev/tty.usbserial-14240
  #   max_brightness: 120
  #   associated_midi_channels:
  #     - Ableton-virtual-midi-ouput LeftSynth
  #   midi_ports_for_changing_mode:
  #     - Ableton-virtual-midi-ouput ChangeModStripTwo
  #     - Ableton-virtual-midi-ouput ChangeMod
  #   shapes:
  #     -
  #       - 34
  #       - 52
  #       - 50
  #     -
  #       - 24
  #       - 24
  #   active_audio_channel_index: 0
  #   active_color_index: 0
  #   active_shape_index: 0
  #   is_reverse: false
  #   bpm: 120
  #   is_mirror: false
  #   active_color_scheme_index: 0
  #   color_schemes:
  #     -
  #       - "#FF00C8"
  #       - "#00EDFF"
  #   active_visualizer_effect: energy

  -
    serial_port_name: /dev/tty.usbserial-14230
    max_brightness: 120
    associated_midi_channels:
      - Ableton-virtual-midi-ouput LeftSynth
    midi_ports_for_changing_mode:
      - Ableton-virtual-midi-ouput ChangeMod
    shapes:
      -
        - 148
        # - 250
      -
        - 64
        - 64
        # - 125
        # - 125
      -
        - 32
        - 32
        - 32
        - 32
        # - 64
        # - 64
        # - 64
        # - 64

    active_audio_channel_index: 0
    active_color_index: 0
    active_shape_index: 0
    is_reverse: false
    bpm: 120
    is_mirror: true
    active_color_scheme_index: 0
    color_schemes:
      -
        - "#FF00C8"
        - "#00EDFF"
    active_visualizer_effect: energy

...  # document end
