---  # document start

################
# CONFIG FILE  #
################

# -
#   - 20
#   - 18
#   - 18
#   - 18

# -
#   - 34
#   - 52
#   - 50

fps: 60

display_shell_interface: false
display_audio_interface: false

n_rolling_history: 4
number_of_audio_samples: 24

audio_ports:
  -
    name: Built-in Microphone
    min_frequency: 200
    max_frequency: 12000
    sampling_rate: 44000
    number_of_audio_samples: 24
    min_volume_threshold: 1e-7
  # -
  #   name: Loopback Audio 2
  #   min_frequency: 200
  #   max_frequency: 12000
  #   sampling_rate: 44000
  #   number_of_audio_samples: 24
  #   min_volume_threshold: 1e-7

strips:
  -
    name: infinite_mirror
    serial_port_name: /dev/tty.usbserial-14210
    max_brightness: 120
    associated_midi_channels:
      - Ableton-virtual-midi-ouput RightSynth
      - Ableton-virtual-midi-ouput LeftSynth
    midi_ports_for_changing_mode:
      - Ableton-virtual-midi-ouput ChangeModStripOne
      - Ableton-virtual-midi-ouput ChangeMod
      - LPK25
    shapes:
      -
        - 20
        - 18
        - 18
        - 18
      -
        - 30
        - 12
        - 30
        - 12
    active_audio_channel_index: 0
    active_color_index: 0
    active_shape_index: 0
    is_reverse: false
    bpm: 120
    is_mirror: true
    active_color_scheme_index: 0
    color_schemes:
      - # pink blue
        - "#FF00C8"
        - "#00EDFF"
      - # orange blue
        - "#FFA200"
        - "#00C6FF"
      - # red green
        - "#FF002E"
        - "#00FFA4"
      - # purple green
        - "#F900FF"
        - "#22FF00"
      - # blue yellow
        - "#0024FF"
        - "#FFE500"
      -
        - red
        - green
        - blue
    active_visualizer_effect: scroll

  -
    name: office_corner
    serial_port_name: /dev/tty.usbserial-14220
    max_brightness: 120
    associated_midi_channels:
      - Ableton-virtual-midi-ouput LeftSynth
    midi_ports_for_changing_mode:
      - Ableton-virtual-midi-ouput ChangeModStripTwo
      - Ableton-virtual-midi-ouput ChangeMod
      - LPK25
    shapes:
      -
        - 148
        - 104
      -
        - 64
        - 64
        - 52
        - 52
      -
        - 32
        - 32
        - 32
        - 32
        - 26
        - 26
        - 26
        - 26

    active_audio_channel_index: 0
    active_color_index: 0
    active_shape_index: 0
    is_reverse: false
    bpm: 120
    is_mirror: true
    active_color_scheme_index: 0
    color_schemes:
      - # pink blue
        - "#FF00C8"
        - "#00EDFF"
      - # orange blue
        - "#FFA200"
        - "#00C6FF"
      - # red green
        - "#FF002E"
        - "#00FFA4"
      - # purple green
        - "#F900FF"
        - "#22FF00"
      - # blue yellow
        - "#0024FF"
        - "#FFE500"
      -
        - red
        - green
        - blue
    active_visualizer_effect: scroll

  -
    name: undefined
    serial_port_name: /dev/tty.usbserial-14230
    max_brightness: 120
    associated_midi_channels:
      - Ableton-virtual-midi-ouput LeftSynth
    midi_ports_for_changing_mode:
      - Ableton-virtual-midi-ouput ChangeMod
      - LPK25
    shapes:
      -
        - 252
      -
        - 64
        - 64
        - 64
        - 64
      -
        - 32
        - 32
        - 32
        - 32
        - 32
        - 32
        - 32

    active_audio_channel_index: 0
    active_color_index: 0
    active_shape_index: 0
    is_reverse: false
    bpm: 120
    is_mirror: true
    active_color_scheme_index: 0
    color_schemes:
      - # pink blue
        - "#FF00C8"
        - "#00EDFF"
      - # orange blue
        - "#FFA200"
        - "#00C6FF"
      - # red green
        - "#FF002E"
        - "#00FFA4"
      - # purple green
        - "#F900FF"
        - "#22FF00"
      - # blue yellow
        - "#0024FF"
        - "#FFE500"
      -
        - red
        - green
        - blue
    active_visualizer_effect: scroll

  -
    name: office_front
    serial_port_name: /dev/tty.usbserial-14240
    max_brightness: 120
    associated_midi_channels:
      - Ableton-virtual-midi-ouput LeftSynth
    midi_ports_for_changing_mode:
      - Ableton-virtual-midi-ouput ChangeMod
      - LPK25
    shapes:
      -
        - 148
        - 104
      -
        - 64
        - 64
        - 52
        - 52
      -
        - 32
        - 32
        - 32
        - 32
        - 26
        - 26
        - 26
        - 26

    active_audio_channel_index: 0
    active_color_index: 0
    active_shape_index: 0
    is_reverse: false
    bpm: 120
    is_mirror: true
    active_color_scheme_index: 0
    color_schemes:
      - # pink blue
        - "#FF00C8"
        - "#00EDFF"
      - # orange blue
        - "#FFA200"
        - "#00C6FF"
      - # red green
        - "#FF002E"
        - "#00FFA4"
      - # purple green
        - "#F900FF"
        - "#22FF00"
      - # blue yellow
        - "#0024FF"
        - "#FFE500"
      -
        - red
        - green
        - blue
    active_visualizer_effect: scroll

...  # document end
