---  # document start

################
# CONFIG FILE  #
################

#BASS 60 to 250 Hz
#MID 300 to 5000 Hz.
#TREBLE 2048 to 16384 Hz

desirated_framerate: 60
display_interface: True

audio_ports:

  -
    name: Built-in Microphone
    min_frequency: 200
    max_frequency: 12000
  # -
  #   name: 'AK5371                   '
  #   min_frequency: 200
  #   max_frequency: 12000

strips:
  -
    name: Front Desk
    serial_port_name: /dev/tty.usbserial-14210

    midi_ports_for_visualization:
      - USB MIDI Interface
    midi_ports_for_changing_mode:
      - LPK25

    active_state_index: 0

    physical_shape:
      - 80

  -
    name: New Config
    serial_port_name: /dev/tty.usbserial-14240

    midi_ports_for_visualization:
      - USB MIDI Interface
    midi_ports_for_changing_mode:
      - LPK25

    active_state_index: 0

    physical_shape:
      - 80


states:
  -
    name: "Mirrored Energy light blue"
    active_visualizer_effect: energy
    active_propagation_curve: ease_in

    active_audio_channel_index: 0
    audio_channel_min_frequency: 200
    audio_channel_max_frequency: 12000

    active_shape_index: 0
    shapes:
      -
        - 112
      -
        - 56
        - 56
      -
        - 28
        - 28
      -
        - 14
        - 14
        - 14
        - 14

    active_color_scheme_index: 0
    color_schemes:
      -
        - red
        - green
        - blue

    is_reverse: true
    is_mirror: true
    time_interval: 5
    chunk_size: 5
    max_brightness: 55

  -
    name: "Fast Scroll yellow and pink"
    active_visualizer_effect: scroll
    active_propagation_curve: ease_in

    active_audio_channel_index: 0
    audio_channel_min_frequency: 200
    audio_channel_max_frequency: 12000

    active_shape_index: 0
    shapes:
      -
        - 126
        - 126

    active_color_scheme_index: 0
    color_schemes:
      -
        - yellow
        - pink

    is_reverse: false
    is_mirror: false
    time_interval: 225
    chunk_size: 10
    max_brightness: 155

...  # document end
