---  # document start

################
# CONFIG FILE  #
################

desirated_framerate: 60
display_interface: True

audio_ports:

  -
    name: Built-in Microphone
    min_frequency: 200
    max_frequency: 12000

strips:
  -
    name: Front Desk
    serial_port_name: /dev/tty.usbserial-14210

    midi_ports_for_visualization:
      - "Audio2Led Synth"
    midi_ports_for_changing_mode:
      - "Audio2Led ChangeMod"

    active_state_index: 0

    physical_shape:
      - 80

states:
  -
    name: "Simple channel instensity"
    active_visualizer_effect: piano_scroll
    active_propagation_curve: ease_in

    active_audio_channel_index: 0
    audio_samples_filter_min: 0
    audio_samples_filter_max: 24

    active_shape_index: 0
    shapes:
      -
        - 80
      -
        - 20
        - 20
        - 20
        - 20

    active_color_scheme_index: 0
    color_schemes:
      -
        - DodgerBlue
        - Blue

    is_reverse: false
    is_mirror: false
    time_interval: 50
    chunk_size: 5
    max_brightness: 55


  -
    name: "Simple channel flash"
    active_visualizer_effect: channel_flash
    active_propagation_curve: ease_in

    active_audio_channel_index: 0
    audio_samples_filter_min: 0
    audio_samples_filter_max: 24

    active_shape_index: 0
    shapes:
      -
        - 10
        - 10
        - 10
        - 10
        - 10
        - 10
        - 10
        - 10

    active_color_scheme_index: 0
    color_schemes:
      -
        - blue

    is_reverse: false
    is_mirror: false
    time_interval: 50
    chunk_size: 5
    max_brightness: 55

  -
    name: "Simple blue and pink energy"
    active_visualizer_effect: energy
    active_propagation_curve: ease_in

    active_audio_channel_index: 0
    audio_samples_filter_min: 0
    audio_samples_filter_max: 24

    active_shape_index: 0
    shapes:
      -
        - 80

    active_color_scheme_index: 0
    color_schemes:
      -
        - "#FF00C8"
        - "#00C6FF"

    is_reverse: false
    is_mirror: true
    time_interval: 50
    chunk_size: 5
    max_brightness: 55

  -
    name: "Classical low speed rgb mirrored scroll"
    active_visualizer_effect: scroll
    active_propagation_curve: ease_out

    active_audio_channel_index: 0
    audio_samples_filter_min: 0
    audio_samples_filter_max: 24

    active_shape_index: 0
    shapes:
      -
        - 80

    active_color_scheme_index: 0
    color_schemes:
      -
        - red
        - green
        - blue

    is_reverse: false
    is_mirror: true
    time_interval: 5
    chunk_size: 20
    max_brightness: 50

...  # document end
